# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 966a67cb98d8a67b27b61db8f1093fe2449a68aaecdf077639d1a8969b8d47e67c1e22c074548c2ad76b8df99a39234bc216647fe880cbd0538d65cfb0657165

test:
  secret_key_base: cf06ac6f682a21d3099ea2bae2ecb35978da994b977eab3dabe5e8ac72453aae21eec5c3f5b413656956a571742cf10a6b4d40e4e511a57401f065f7090ac29e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
