# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 966a67cb98d8a67b27b61db8f1093fe2449a68aaecdf077639d1a8969b8d47e67c1e22c074548c2ad76b8df99a39234bc216647fe880cbd0538d65cfb0657165

  FACEBOOK_API_ID: "1491765017555568"
  FACEBOOK_API_SECRET: "061c501432ba690d2f25f8a9c3fc5ac9"

  GOOGLE_MAPS_KEY: "AIzaSyCSOxMnIVJxZQQ-aeHTJDJdLQs084hgTgM"

  STRIPE_SECRET_KEY: "sk_test_EA8atQkXQVCCfZjS2aBy3DLh"
  STRIPE_PUBLISHABLE_KEY: "pk_test_E9bEaTcxL3dT8XGQZ51fbGGw"
  STRIPE_CONNECT_CLIENT_ID: "ca_BMeIeTCUyYo3QIDWGNtdYQwuVuIMrYba"

test:
  secret_key_base: cf06ac6f682a21d3099ea2bae2ecb35978da994b977eab3dabe5e8ac72453aae21eec5c3f5b413656956a571742cf10a6b4d40e4e511a57401f065f7090ac29e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
